export type Language = "en" | "vi";

export const initialLyricGreeting: Record<Language, string> = {
  en: "Hello! I'm your AI Lyric Assistant. Tell me about the vibe, theme, or some keywords, and I'll help you draft polished lyrics.",
  vi: "Chao ban! Toi la tro ly viet loi bai hat bang AI. Hay noi cho toi biet vibe, chu de, hoac vai tu khoa, toi se giup ban phac thao loi bai hat gon va dep.",
};

export const content = {
  en: {
    nav: {
      home: "Home",
      studio: "Studio",
      music: "Music",
      about: "About",
      journal: "Journal",
      contact: "Reach Us",
      begin: "Begin Journey",
      toggleTheme: "Toggle theme",
      toggleLanguage: "Switch language",
    },
    hero: {
      lead: "Where ",
      accent: "dreams",
      bridge: " rise ",
      end: "through the silence.",
      body:
        "We're designing tools for deep thinkers, bold creators, and quiet rebels. Amid the chaos, we build digital spaces for sharp focus and inspired work.",
      cta: "Begin Journey",
      scroll: "Scroll to explore",
    },
    studio: {
      label: "The Studio",
      titleTop: "Crafting digital",
      titleAccent: "sanctuaries.",
      body:
        "Our studio is a laboratory for the senses. We combine cutting-edge technology with timeless design principles to create interfaces that feel as natural as they are powerful.",
      button: "View Projects",
      card1: "Minimalist Architecture",
      card2: "Fluid Interactions",
    },
    about: {
      label: "Our Philosophy",
      titleTop: "We believe in the",
      titleAccent: "power of focus.",
      body:
        "In a world designed to distract, we build for the moments that matter. BreezeBoy was founded on the idea that technology should disappear into the background, leaving only the clarity of your own thoughts.",
      awards: "Global Awards",
      users: "Active Users",
      latency: "Latency Goal",
    },
    journal: {
      label: "The Journal",
      title: "Latest Insights",
      button: "Read All Entries",
      meta: "Design • April 2024",
      cardTitle: "The psychology of minimalist interfaces in the age of AI.",
    },
    ai: {
      label: "The Lab",
      title: "AI Creative Studio",
      body:
        "Experiment with our custom-tuned generative models. From visual manifestations to sonic landscapes.",
      visionTitle: "AI Vision",
      visionMeta: "Image Generation & Remix",
      visionLoading: "Rendering vision...",
      visionSample:
        '"A minimalist sanctuary in the clouds, soft morning light, cinematic atmosphere"',
      visionPlaceholder: "Describe your visual manifestation...",
      visionButton: "Generate Image",
      visionAlt: "AI Generated Vision",
      visionSourceAlt: "Source image",
      lyricTitle: "Lyric Assistant",
      lyricMeta: "Songwriting Partner",
      lyricPlaceholder: "Ask for lyrics, rhymes, or ideas...",
      lyricError: "Sorry, I encountered an error while writing lyrics. Please try again.",
      imageError: "Failed to generate image. Please try again later.",
      noResponse: "No response",
      lyricFailed: "Failed to generate lyrics",
      imageFailed: "Image generation failed",
      noImage: "No image returned",
      downloadName: "breezeboy-vision.png",
    },
    contact: {
      label: "Contact",
      titleTop: "Let's start",
      titleAccent: "something.",
      email: "Email",
      studio: "Studio",
      name: "Name",
      emailField: "Email",
      message: "Message",
      projectPlaceholder: "Tell us about your project...",
      send: "Send Message",
    },
    footer: {
      rights: "© 2024 Breeze Boy Studio. All rights reserved.",
    },
  },
  vi: {
    nav: {
      home: "Trang Chu",
      studio: "Studio",
      music: "Nhac",
      about: "Gioi Thieu",
      journal: "Tap Chi",
      contact: "Lien He",
      begin: "Bat Dau",
      toggleTheme: "Chuyen giao dien",
      toggleLanguage: "Chuyen ngon ngu",
    },
    hero: {
      lead: "Noi ",
      accent: "giac mo",
      bridge: " cat canh ",
      end: "giua lang im.",
      body:
        "Chung toi thiet ke cong cu cho nhung nguoi suy nghi sau, nhung nha sang tao tao bao va nhung ke noi loan lang le. Giua hon loan, chung toi tao ra khong gian so cho su tap trung va cam hung.",
      cta: "Bat Dau",
      scroll: "Cuon de kham pha",
    },
    studio: {
      label: "Studio",
      titleTop: "Kien tao nhung khong gian so",
      titleAccent: "an tinh.",
      body:
        "Studio cua chung toi la mot phong thi nghiem cho giac quan. Chung toi ket hop cong nghe hien dai voi nguyen ly thiet ke vuot thoi gian de tao ra giao dien tu nhien va day suc manh.",
      button: "Xem Du An",
      card1: "Kien Truc Toi Gian",
      card2: "Tuong Tac Mem Mai",
    },
    about: {
      label: "Triet Ly",
      titleTop: "Chung toi tin vao",
      titleAccent: "suc manh cua su tap trung.",
      body:
        "Trong mot the gioi duoc tao ra de gay xao nhang, chung toi xay dung cho nhung khoanh khac thuc su quan trong. BreezeBoy duoc sinh ra tu niem tin rang cong nghe nen lui vao hau canh, chi de lai su ro rang trong suy nghi cua ban.",
      awards: "Giai Thuong Toan Cau",
      users: "Nguoi Dung Hoat Dong",
      latency: "Muc Tieu Do Tre",
    },
    journal: {
      label: "Tap Chi",
      title: "Goc Nhin Moi",
      button: "Doc Tat Ca",
      meta: "Thiet ke • Thang 4 2024",
      cardTitle: "Tam ly hoc cua giao dien toi gian trong ky nguyen AI.",
    },
    ai: {
      label: "Phong Lab",
      title: "AI Creative Studio",
      body:
        "Thu nghiem voi cac mo hinh sinh noi dung duoc tinh chinh cho rieng ban. Tu hinh anh den nhung khong gian am thanh day cam hung.",
      visionTitle: "AI Vision",
      visionMeta: "Tao Anh & Bien Tau",
      visionLoading: "Dang tao hinh anh...",
      visionSample:
        '"Mot noi an tinh toi gian tren may, anh som diu nhe, khong khi dien anh"',
      visionPlaceholder: "Mo ta y tuong hinh anh cua ban...",
      visionButton: "Tao Anh",
      visionAlt: "Anh do AI tao",
      visionSourceAlt: "Anh goc",
      lyricTitle: "Tro Ly Loi Nhac",
      lyricMeta: "Ban dong hanh sang tac",
      lyricPlaceholder: "Hoi ve loi bai hat, van, hoac y tuong...",
      lyricError: "Xin loi, da co loi khi viet loi bai hat. Vui long thu lai.",
      imageError: "Khong the tao anh luc nay. Vui long thu lai sau.",
      noResponse: "Khong co phan hoi",
      lyricFailed: "Khong the tao loi bai hat",
      imageFailed: "Khong the tao anh",
      noImage: "Khong co anh duoc tra ve",
      downloadName: "breezeboy-vision.png",
    },
    contact: {
      label: "Lien He",
      titleTop: "Cung bat dau",
      titleAccent: "mot dieu gi do.",
      email: "Email",
      studio: "Studio",
      name: "Ten",
      emailField: "Email",
      message: "Tin Nhan",
      projectPlaceholder: "Hay ke cho chung toi ve du an cua ban...",
      send: "Gui Tin Nhan",
    },
    footer: {
      rights: "© 2024 Breeze Boy Studio. Da dang ky moi quyen.",
    },
  },
} as const;
